import Image from "next/image";
import Link from "next/link";
import { ArrowRightIcon, ExternalLinkIcon } from "@/components/ui/icons";
import { Tag } from "@/components/ui/tag";
import type { PortfolioProject } from "@/types/portfolio";

export function ProjectCard({ project }: { project: PortfolioProject }) {
  return <article className="group overflow-hidden rounded-2xl border border-white/10 bg-[#141414] transition-all duration-300 hover:-translate-y-1 hover:border-white/20 hover:shadow-2xl hover:shadow-black/30"><Link className="block overflow-hidden border-b border-white/10 bg-[#0b0b0b]" href={`/projects/${project.slug}`}><div className="relative aspect-[16/10] overflow-hidden"><Image src={project.thumbnail} alt={`${project.title} interface`} fill priority={project.priority <= 2} sizes="(max-width: 768px) 100vw, (max-width: 1280px) 50vw, 560px" className="object-cover object-top transition-transform duration-500 group-hover:scale-[1.025]" /></div></Link><div className="flex flex-col gap-5 p-5 sm:p-6"><div className="flex flex-wrap gap-2">{project.categories.map(category => <Tag key={category}>{category}</Tag>)}</div><div><h3 className="text-xl font-semibold tracking-tight">{project.title}</h3><p className="mt-2 line-clamp-3 text-sm leading-relaxed text-[#a8a8a8]">{project.shortDescription}</p></div><div className="flex flex-wrap gap-2">{project.technologies.slice(0, 5).map(technology => <span className="text-xs text-[#8c8c8c]" key={technology}>{technology}</span>)}</div><div className="flex items-center justify-between"><Link className="inline-flex items-center gap-2 text-sm font-medium transition-colors hover:text-[#8db7dc]" href={`/projects/${project.slug}`}>View Project <ArrowRightIcon className="size-4" /></Link>{project.liveUrl && <a aria-label={`Open ${project.title} live demo`} className="flex size-8 items-center justify-center rounded-md border border-white/10 text-[#a8a8a8] transition-colors hover:bg-white/5 hover:text-white" href={project.liveUrl} target="_blank" rel="noreferrer"><ExternalLinkIcon className="size-4" /></a>}</div></div></article>;
}
