import Link from "next/link";
import { buttonStyles } from "@/components/ui/button";
import { ArrowRightIcon, LinkedInIcon } from "@/components/ui/icons";
import { Tag } from "@/components/ui/tag";
import { profile } from "@/data/profile";

export function HeroSection() {
  return <section className="relative flex min-h-svh items-center justify-center overflow-hidden py-24" data-hero-section><div aria-hidden="true" className="hero-aurora" data-testid="hero-aurora"><span className="hero-aurora-layer hero-aurora-left" data-testid="hero-aurora-layer" /><span className="hero-aurora-layer hero-aurora-right" data-testid="hero-aurora-layer" /><span className="hero-aurora-layer hero-aurora-bottom" data-testid="hero-aurora-layer" /><span className="hero-aurora-vignette" /><span className="hero-aurora-grain" /></div><div className="relative z-10 mx-auto flex max-w-5xl flex-col items-center justify-center space-y-6 px-4 text-center"><Tag className="text-[#d7e9f8]">Available for software engineering opportunities</Tag><div className="space-y-4"><h1 className="bg-linear-to-b from-[#dff2fe] to-white bg-clip-text text-5xl font-medium tracking-[-.055em] text-transparent sm:text-6xl md:text-7xl">{profile.name}</h1><p className="mx-auto max-w-4xl text-balance text-2xl font-medium tracking-tight text-white sm:text-3xl md:text-4xl">Full Stack Developer building scalable web applications and AI-powered products.</p></div><p className="mx-auto max-w-2xl text-balance text-base leading-relaxed text-[#a8a8a8] sm:text-lg">{profile.heroDescription}</p><div className="flex flex-col items-center gap-3 sm:flex-row"><Link className={buttonStyles("primary", "h-10 px-5")} href="/projects">View Projects <ArrowRightIcon className="size-4" /></Link><Link className={buttonStyles("outline", "h-10 px-5")} href="/contact">Contact Me</Link><a aria-label="LinkedIn profile" className={buttonStyles("ghost", "size-10 px-0")} href={profile.linkedin} target="_blank" rel="noreferrer"><LinkedInIcon className="size-4" /></a></div></div></section>;
}
